/**
 * Object Schemas Index
 * Auto-generated - do not edit manually
 */

export * from './DateTimeFieldUpdateOperationsInput.schema';
export * from './DateTimeFilter.schema';
export * from './DateTimeWithAggregatesFilter.schema';
export * from './FloatNullableFilter.schema';
export * from './FloatNullableWithAggregatesFilter.schema';
export * from './IntFieldUpdateOperationsInput.schema';
export * from './IntFilter.schema';
export * from './IntWithAggregatesFilter.schema';
export * from './NestedDateTimeFilter.schema';
export * from './NestedDateTimeWithAggregatesFilter.schema';
export * from './NestedFloatFilter.schema';
export * from './NestedFloatNullableFilter.schema';
export * from './NestedFloatNullableWithAggregatesFilter.schema';
export * from './NestedIntFilter.schema';
export * from './NestedIntNullableFilter.schema';
export * from './NestedIntWithAggregatesFilter.schema';
export * from './NestedStringFilter.schema';
export * from './NestedStringWithAggregatesFilter.schema';
export * from './NullableFloatFieldUpdateOperationsInput.schema';
export * from './ProductArgs.schema';
export * from './ProductAvgAggregateInput.schema';
export * from './ProductAvgOrderByAggregateInput.schema';
export * from './ProductCountAggregateInput.schema';
export * from './ProductCountOrderByAggregateInput.schema';
export * from './ProductCreateInput.schema';
export * from './ProductCreateManyInput.schema';
export * from './ProductMaxAggregateInput.schema';
export * from './ProductMaxOrderByAggregateInput.schema';
export * from './ProductMinAggregateInput.schema';
export * from './ProductMinOrderByAggregateInput.schema';
export * from './ProductOrderByWithAggregationInput.schema';
export * from './ProductOrderByWithRelationInput.schema';
export * from './ProductScalarWhereWithAggregatesInput.schema';
export * from './ProductSelect.schema';
export * from './ProductSumAggregateInput.schema';
export * from './ProductSumOrderByAggregateInput.schema';
export * from './ProductUncheckedCreateInput.schema';
export * from './ProductUncheckedUpdateInput.schema';
export * from './ProductUncheckedUpdateManyInput.schema';
export * from './ProductUpdateInput.schema';
export * from './ProductUpdateManyMutationInput.schema';
export * from './ProductWhereInput.schema';
export * from './ProductWhereUniqueInput.schema';
export * from './SortOrderInput.schema';
export * from './StringFieldUpdateOperationsInput.schema';
export * from './StringFilter.schema';
export * from './StringWithAggregatesFilter.schema';
