import { Rackets } from "./schema";

export const products = [
  {
    id: "ULID001",
    brand: "Yonex",
    name: "Astrox 100 ZZ",
    slug: "astrox-100-zz",
    weight: "3U",
    sku: "YON-ASR-001",
    pric: 1200000,
    stockQuantity: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "ULID002",
    brand: "Victor",
    name: "Thruster Ryuga II",
    slug: "thruster-ryuga-ii",
    weight: "4U",
    sku: "VIC-RYU-001",
    price: 3000000,
    stockQuantity: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "ULID003",
    brand: "Li-Ning",
    name: "BladeX 900",
    slug: "bladex-900",
    weight: "2U",
    sku: "LIN-BDX-001",
    price: 2500000,
    stockQuantity: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "ULID004",
    brand: "Hundred",
    name: "Nitrix Volta 70",
    slug: "nitrix-volta-70",
    weight: "5U",
    sku: "HUN-NVX-001",
    price: 1500000,
    stockQuantity: 15,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "ULID005",
    brand: "Apacs",
    name: "Ziggler LHI Pro III",
    slug: "ziggler-lhi-pro-iii",
    weight: "3U",
    sku: "APA-ZLP-001",
    price: 800000,
    stockQuantity: 20,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "ULID006",
    brand: "Yonex",
    name: "Voltage Z-Force II LCW Limited",
    slug: "voltage-z-force-ii-lcw-limited",
    weight: "3U",
    sku: "YON-VZF-001",
    price: 2000000,
    stockQuantity: 15,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "ULID007",
    brand: "Felet",
    name: "Woven 1000",
    slug: "woven-1000",
    weight: "4U",
    sku: "FEL-WVN-001",
    price: 1800000,
    stockQuantity: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
